package com.core_java.oops.ExceptionTest;

public class Exception7 {

	public static void main(String[] args) {
		try
		{
			return;
			
		}
		finally
		{
			System.out.println("finally");
		}

	}

}
